#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "AgentPOS for Alexa+: credentials the code cannot create for you"

# ── 1. Shared bearer between the Bridge and the Simulator ─────────────────
stage "Bridge bearer token"
say "The Simulator dials the Bridge with a bearer token. Both read BRIDGE_BEARER_TOKEN from .env."
current=$(_existing BRIDGE_BEARER_TOKEN || true)
if [[ -z "$current" || "$current" == "change-me" ]]; then
  BRIDGE_BEARER_TOKEN=$(head -c 24 /dev/urandom | base64 | tr '+/' '-_' | tr -d '=')
  note "generated a random token for this machine"
else
  BRIDGE_BEARER_TOKEN="$current"
  note "keeping the existing token"
fi
write_env BRIDGE_BEARER_TOKEN "$BRIDGE_BEARER_TOKEN"

# ── 2. AWS identity for Bedrock ───────────────────────────────────────────
stage "AWS: an identity that may call Bedrock"
say "The agents call Amazon Bedrock in us-east-1. Create an IAM user for this laptop only,"
say "with the managed policy AmazonBedrockFullAccess (or a narrower inline policy with"
say "bedrock:InvokeModel, bedrock:InvokeModelWithResponseStream and bedrock:ListFoundationModels)."
open_url "https://us-east-1.console.aws.amazon.com/iam/home#/users/create"
step "Users -> Create user -> name it agentpos-alexa-dev -> Attach policies directly -> AmazonBedrockFullAccess -> Create."
step "Open the user -> Security credentials -> Create access key -> Command Line Interface -> Create."
ask AWS_ACCESS_KEY_ID "Paste the Access key ID (starts with AKIA):"
ask_secret AWS_SECRET_ACCESS_KEY "Paste the Secret access key (hidden):"
ask AWS_REGION "Region for Bedrock and AgentCore [us-east-1]:"
AWS_REGION="${AWS_REGION:-us-east-1}"
write_env AWS_ACCESS_KEY_ID "$AWS_ACCESS_KEY_ID"
write_env AWS_SECRET_ACCESS_KEY "$AWS_SECRET_ACCESS_KEY"
write_env AWS_REGION "$AWS_REGION"
warn "These keys stay in .env on this machine. Never commit .env; rotate the key when the hackathon ends."

# ── 3. Bedrock model access ───────────────────────────────────────────────
stage "Bedrock: enable the two models"
say "Bedrock serves a model only after you request access to it in the console."
open_url "https://${AWS_REGION}.console.aws.amazon.com/bedrock/home?region=${AWS_REGION}#/modelaccess"
step "Modify model access -> tick Amazon Nova 2 Lite and the newest Anthropic Claude Sonnet -> Next -> Submit."
step "Wait until both show Access granted (usually under a minute)."
pause "Press Enter when both models show Access granted."

# ── 4. Verify with the AWS CLI and pin the model ids ──────────────────────
stage "Bedrock: verify and pin the model ids"
say "Listing the Anthropic and Amazon models your account can invoke in ${AWS_REGION} (no AWS CLI needed):"
if command -v node >/dev/null 2>&1 && [[ -f scripts/bedrock-check.mjs ]]; then
  AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" AWS_REGION="$AWS_REGION" \
    node scripts/bedrock-check.mjs 2>/dev/null | grep -vE "^(FAIL|OK|region)" || warn "the listing failed; check the keys and the region, then re-run this wizard"
  note "A model that lists only INFERENCE_PROFILE needs the cross-region id that starts with us. (the defaults below already do)."
else
  warn "node or scripts/bedrock-check.mjs not found; use the ids from the Bedrock console's model catalog."
fi
ask BEDROCK_MODEL_FAST "Model id for frequent cheap steps [us.amazon.nova-2-lite-v1:0]:"
ask BEDROCK_MODEL_STRONG "Model id for critical decisions (Claude Sonnet) [us.anthropic.claude-sonnet-4-6]:"
write_env BEDROCK_MODEL_FAST "${BEDROCK_MODEL_FAST:-us.amazon.nova-2-lite-v1:0}"
write_env BEDROCK_MODEL_STRONG "${BEDROCK_MODEL_STRONG:-us.anthropic.claude-sonnet-4-6}"

# ── 5. Stripe test mode for the merchant PSP rail ─────────────────────────
stage "Stripe: test mode keys for the demo store"
say "The merchant PSP rail tokenizes cards in the client with Stripe's PUBLISHABLE test key."
say "The SECRET key belongs to the store (its WooCommerce Stripe settings) and is never stored here (hard rule 1)."
open_url "https://dashboard.stripe.com/test/apikeys"
step "Make sure the dashboard is in Test mode (toggle at the top right)."
step "Copy the Publishable key (starts with pk_test_). Do not copy the secret key."
ask STRIPE_PUBLISHABLE_KEY "Paste the publishable test key (pk_test_...):"
if [[ "$STRIPE_PUBLISHABLE_KEY" == sk_* ]]; then
  warn "That is a SECRET key. It must not live in this repo. Not saved."
else
  write_env STRIPE_PUBLISHABLE_KEY "$STRIPE_PUBLISHABLE_KEY"
fi
step "In the store's WooCommerce Stripe settings, enable test mode and paste the test SECRET key there."
pause "Press Enter once the store has its own test keys."

# ── 6. Smoke test ─────────────────────────────────────────────────────────
stage "Smoke test"
say "Run these in three terminals from the repo root:"
note "  pnpm dev:fixture-store"
note "  AGENTPOS_STORE_URL=http://127.0.0.1:8790 pnpm dev:bridge"
note "  pnpm dev:simulator      (open http://127.0.0.1:8788)"
say "With AWS keys in .env the Household agent runs on Bedrock; without them the Simulator says Recorded mode."
pause "Press Enter to finish."

finish
